<a href="https://colab.research.google.com/github/akashms011-create/demo/blob/main/Acquisition_casestudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1
import pandas as pd
import sqlite3

In [ ]:
population=pd.read_csv('population.csv')

In [ ]:
population.head()

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

In [ ]:
population.dtypes

country       object
population     int64
dtype: object

In [ ]:
population.shape

(25, 2)

In [ ]:
#2
gdp = pd.read_excel("gdp.xlsx")

In [ ]:
gdp.columns

Index(['Country', 'GDP'], dtype='object')

In [ ]:
gdp.dtypes

Country    object
GDP         int64
dtype: object

In [ ]:
#3
internet = pd.read_json("internet_users.json")
internet=pd.DataFrame(internet)
internet.head()

         country  internet_users
0  United States       312000000
1          China      1080000000
2          India       850000000
3          Japan       118000000
4        Germany        79000000

In [ ]:
#4
literacy = pd.read_xml("literacy_rate.xml")
literacy=pd.DataFrame(literacy)
print(literacy.head())

            name  literacy_rate
0  United States           99.0
1          China           97.2
2          India           77.7
3          Japan           99.0
4        Germany           99.0

In [ ]:
#5
print(population.shape)
print(population.columns)
print(population.dtypes)
print(population.isnull().sum())
print(population.duplicated().sum())

(25, 2)
Index(['country', 'population'], dtype='object')
country       object
population     int64
dtype: object
country       0
population    0
dtype: int64
0

In [ ]:
print(gdp.shape)
print(gdp.columns)
print(gdp.dtypes)
print(gdp.isnull().sum())
print(gdp.duplicated().sum())

(25, 2)
Index(['Country', 'GDP'], dtype='object')
Country    object
GDP         int64
dtype: object
Country    0
GDP        0
dtype: int64
0

In [ ]:
print(internet.shape)
print(internet.columns)
print(internet.dtypes)
print(internet.isnull().sum())
print(internet.duplicated().sum())

(25, 2)
Index(['country', 'internet_users'], dtype='object')
country           object
internet_users     int64
dtype: object
country           0
internet_users    0
dtype: int64
0

In [ ]:
print(literacy.shape)
print(literacy.columns)
print(literacy.dtypes)
print(literacy.isnull().sum())
print(literacy.duplicated().sum())

(25, 2)
Index(['name', 'literacy_rate'], dtype='object')
name              object
literacy_rate    float64
dtype: object
name             0
literacy_rate    0
dtype: int64
0

In [ ]:
#6
population.rename(columns={'Country':'country'},inplace=True)
gdp.rename(columns={'Country':'country'},inplace=True)
internet.rename(columns={'Country':'country'},inplace=True)
literacy.rename(columns={'Country':'country'},inplace=True)

In [ ]:
#7
population["population"] = pd.to_numeric(population["population"])

gdp["GDP"] = pd.to_numeric(gdp["GDP"])

internet["internet_users"] = pd.to_numeric(internet["internet_users"])

literacy["literacy_rate"] = pd.to_numeric(literacy["literacy_rate"])

In [ ]:
#8
literacy.rename(columns={'name':'country'},inplace=True)

In [ ]:
merged = population.merge(gdp,on="country")

merged = merged.merge(internet,on="country")

merged = merged.merge(literacy,on="country")

print(merged.head())

         country  population       GDP  internet_users  literacy_rate
0  United States   331002651  30500000       312000000           99.0
1          China  1411778724  19230000      1080000000           97.2
2          India  1380004385   4187000       850000000           77.7
3          Japan   125836021   4180000       118000000           99.0
4        Germany    83240525   4744000        79000000           99.0

In [ ]:
#9
merged["Internet Penetration (%)"] = (
merged["internet_users"] /
merged["population"] *100
).round(2)

In [ ]:
merged["GDP Per Capita"] = (
merged["GDP"] /
merged["population"]
).round(2)
merged

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06
5,United Kingdom,67886011,3839000,66000000,99.0,97.22,0.06
6,France,65273511,3211000,62000000,99.0,94.98,0.05
7,Italy,60461826,2420000,56000000,99.0,92.62,0.04
8,Canada,38005238,2250000,36000000,99.0,94.72,0.06
9,Australia,25687041,1880000,24000000,99.0,93.43,0.07
10,Brazil,212559417,2330000,181000000,93.2,85.15,0.01
11,Russia,145934462,2200000,125000000,99.7,85.65,0.02
12,South Korea,51780579,1800000,50000000,98.8,96.56,0.03
13,Spain,46754778,1710000,44000000,98.6,94.11,0.04
14,Mexico,128932753,1810000,102000000,95.4,79.11,0.01
15,Indonesia,273523615,1500000,212000000,96.0,77.51,0.01
16,Saudi Arabia,34813871,1100000,34000000,97.3,97.66,0.03
17,Turkey,84339067,1350000,69000000,96.7,81.81,0.02
18,South Africa,59308690,410000,43000000,95.0,72.50,0.01
19,Argentina,45195774,640000,41000000,99.1,90.72,0.01
20,Netherlands,17441139,1150000,17000000,99.0,97.47,0.07
21,Switzerland,8654622,940000,8500000,99.0,98.21,0.11
22,Sweden,10353442,650000,10100000,99.0,97.55,0.06
23,Norway,5421241,580000,5300000,100.0,97.76,0.11
24,Singapore,5850342,530000,5600000,97.5,95.72,0.09

In [ ]:
#10
connection = sqlite3.connect("country.db")

merged.to_sql(
"country_statistics",
connection,
if_exists="replace",
index=False
)

print("Database Created Successfully")

Database Created Successfully

In [ ]:
#11
result = pd.read_sql(
"SELECT * FROM country_statistics LIMIT 5",
connection
)

print(result)

         country  population       GDP  internet_users  literacy_rate  \
0  United States   331002651  30500000       312000000           99.0
1          China  1411778724  19230000      1080000000           97.2
2          India  1380004385   4187000       850000000           77.7
3          Japan   125836021   4180000       118000000           99.0
4        Germany    83240525   4744000        79000000           99.0

   Internet Penetration (%)  GDP Per Capita
0                     94.26            0.09
1                     76.50            0.01
2                     61.59            0.00
3                     93.77            0.03
4                     94.91            0.06

In [ ]:
print(
merged.nlargest(5,"GDP")
)

         country  population       GDP  internet_users  literacy_rate  \
0  United States   331002651  30500000       312000000           99.0
1          China  1411778724  19230000      1080000000           97.2
4        Germany    83240525   4744000        79000000           99.0
2          India  1380004385   4187000       850000000           77.7
3          Japan   125836021   4180000       118000000           99.0

   Internet Penetration (%)  GDP Per Capita
0                     94.26            0.09
1                     76.50            0.01
4                     94.91            0.06
2                     61.59            0.00
3                     93.77            0.03

In [ ]:
print(
merged.nlargest(5,"population")
)

          country  population       GDP  internet_users  literacy_rate  \
1           China  1411778724  19230000      1080000000           97.2
2           India  1380004385   4187000       850000000           77.7
0   United States   331002651  30500000       312000000           99.0
15      Indonesia   273523615   1500000       212000000           96.0
10         Brazil   212559417   2330000       181000000           93.2

    Internet Penetration (%)  GDP Per Capita
1                      76.50            0.01
2                      61.59            0.00
0                      94.26            0.09
15                     77.51            0.01
10                     85.15            0.01

In [ ]:
print(
    merged["literacy_rate"].mean
)

<bound method Series.mean of 0      99.0
1      97.2
2      77.7
3      99.0
4      99.0
5      99.0
6      99.0
7      99.0
8      99.0
9      99.0
10     93.2
11     99.7
12     98.8
13     98.6
14     95.4
15     96.0
16     97.3
17     96.7
18     95.0
19     99.1
20     99.0
21     99.0
22     99.0
23    100.0
24     97.5
Name: literacy_rate, dtype: float64>

In [ ]:
print(
    merged[
        merged["literacy_rate"]>90
    ]
)

           country  population       GDP  internet_users  literacy_rate  \
0    United States   331002651  30500000       312000000           99.0
1            China  1411778724  19230000      1080000000           97.2
3            Japan   125836021   4180000       118000000           99.0
4          Germany    83240525   4744000        79000000           99.0
5   United Kingdom    67886011   3839000        66000000           99.0
6           France    65273511   3211000        62000000           99.0
7            Italy    60461826   2420000        56000000           99.0
8           Canada    38005238   2250000        36000000           99.0
9        Australia    25687041   1880000        24000000           99.0
10          Brazil   212559417   2330000       181000000           93.2
11          Russia   145934462   2200000       125000000           99.7
12     South Korea    51780579   1800000        50000000           98.8
13           Spain    46754778   1710000        44000000           98.6
14          Mexico   128932753   1810000       102000000           95.4
15       Indonesia   273523615   1500000       212000000           96.0
16    Saudi Arabia    34813871   1100000        34000000           97.3
17          Turkey    84339067   1350000        69000000           96.7
18    South Africa    59308690    410000        43000000           95.0
19       Argentina    45195774    640000        41000000           99.1
20     Netherlands    17441139   1150000        17000000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Sweden    10353442    650000        10100000           99.0
23          Norway     5421241    580000         5300000          100.0
24       Singapore     5850342    530000         5600000           97.5

    Internet Penetration (%)  GDP Per Capita
0                      94.26            0.09
1                      76.50            0.01
3                      93.77            0.03
4                      94.91            0.06
5                      97.22            0.06
6                      94.98            0.05
7                      92.62            0.04
8                      94.72            0.06
9                      93.43            0.07
10                     85.15            0.01
11                     85.65            0.02
12                     96.56            0.03
13                     94.11            0.04
14                     79.11            0.01
15                     77.51            0.01
16                     97.66            0.03
17                     81.81            0.02
18                     72.50            0.01
19                     90.72            0.01
20                     97.47            0.07
21                     98.21            0.11
22                     97.55            0.06
23                     97.76            0.11
24                     95.72            0.09

In [ ]:
print(
    merged[
        merged["Internet Penetration (%)"]>70
    ]
)

           country  population       GDP  internet_users  literacy_rate  \
0    United States   331002651  30500000       312000000           99.0
1            China  1411778724  19230000      1080000000           97.2
3            Japan   125836021   4180000       118000000           99.0
4          Germany    83240525   4744000        79000000           99.0
5   United Kingdom    67886011   3839000        66000000           99.0
6           France    65273511   3211000        62000000           99.0
7            Italy    60461826   2420000        56000000           99.0
8           Canada    38005238   2250000        36000000           99.0
9        Australia    25687041   1880000        24000000           99.0
10          Brazil   212559417   2330000       181000000           93.2
11          Russia   145934462   2200000       125000000           99.7
12     South Korea    51780579   1800000        50000000           98.8
13           Spain    46754778   1710000        44000000           98.6
14          Mexico   128932753   1810000       102000000           95.4
15       Indonesia   273523615   1500000       212000000           96.0
16    Saudi Arabia    34813871   1100000        34000000           97.3
17          Turkey    84339067   1350000        69000000           96.7
18    South Africa    59308690    410000        43000000           95.0
19       Argentina    45195774    640000        41000000           99.1
20     Netherlands    17441139   1150000        17000000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Sweden    10353442    650000        10100000           99.0
23          Norway     5421241    580000         5300000          100.0
24       Singapore     5850342    530000         5600000           97.5

    Internet Penetration (%)  GDP Per Capita
0                      94.26            0.09
1                      76.50            0.01
3                      93.77            0.03
4                      94.91            0.06
5                      97.22            0.06
6                      94.98            0.05
7                      92.62            0.04
8                      94.72            0.06
9                      93.43            0.07
10                     85.15            0.01
11                     85.65            0.02
12                     96.56            0.03
13                     94.11            0.04
14                     79.11            0.01
15                     77.51            0.01
16                     97.66            0.03
17                     81.81            0.02
18                     72.50            0.01
19                     90.72            0.01
20                     97.47            0.07
21                     98.21            0.11
22                     97.55            0.06
23                     97.76            0.11
24                     95.72            0.09

In [ ]:
print(
merged.nlargest(
5,
"GDP Per Capita"
)
)

          country  population       GDP  internet_users  literacy_rate  \
21    Switzerland     8654622    940000         8500000           99.0
23         Norway     5421241    580000         5300000          100.0
0   United States   331002651  30500000       312000000           99.0
24      Singapore     5850342    530000         5600000           97.5
9       Australia    25687041   1880000        24000000           99.0

    Internet Penetration (%)  GDP Per Capita
21                     98.21            0.11
23                     97.76            0.11
0                      94.26            0.09
24                     95.72            0.09
9                      93.43            0.07

In [ ]:
print(
merged["population"].sum()
)

4720039725

In [ ]:
print(
merged["Internet Penetration (%)"].mean()
)

89.6596

In [ ]:
print(
merged.nlargest(
1,
"internet_users"
)
)

  country  population       GDP  internet_users  literacy_rate  \
1   China  1411778724  19230000      1080000000           97.2

   Internet Penetration (%)  GDP Per Capita
1                      76.5            0.01

In [ ]:
print(
merged["literacy_rate"].corr(
merged["Internet Penetration (%)"]
)
)

0.77279756813985

In [ ]:
query='''SELECT *
FROM country_statistics
ORDER BY GDP DESC
LIMIT 5;'''

result=pd.read_sql(query,connection)
display(result)

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,Germany,83240525,4744000,79000000,99.0,94.91,0.06
3,India,1380004385,4187000,850000000,77.7,61.59,0.00
4,Japan,125836021,4180000,118000000,99.0,93.77,0.03

In [ ]:
query='''SELECT AVG(Literacy_Rate)
FROM country_statistics;'''
result=pd.read_sql(query,connection)
display(result)

   AVG(Literacy_Rate)
0              97.248

In [ ]:
query='''SELECT *
FROM country_statistics
WHERE Literacy_Rate>90;'''

result=pd.read_sql(query,connection)
display(result)

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,Japan,125836021,4180000,118000000,99.0,93.77,0.03
3,Germany,83240525,4744000,79000000,99.0,94.91,0.06
4,United Kingdom,67886011,3839000,66000000,99.0,97.22,0.06
5,France,65273511,3211000,62000000,99.0,94.98,0.05
6,Italy,60461826,2420000,56000000,99.0,92.62,0.04
7,Canada,38005238,2250000,36000000,99.0,94.72,0.06
8,Australia,25687041,1880000,24000000,99.0,93.43,0.07
9,Brazil,212559417,2330000,181000000,93.2,85.15,0.01
10,Russia,145934462,2200000,125000000,99.7,85.65,0.02
11,South Korea,51780579,1800000,50000000,98.8,96.56,0.03
12,Spain,46754778,1710000,44000000,98.6,94.11,0.04
13,Mexico,128932753,1810000,102000000,95.4,79.11,0.01
14,Indonesia,273523615,1500000,212000000,96.0,77.51,0.01
15,Saudi Arabia,34813871,1100000,34000000,97.3,97.66,0.03
16,Turkey,84339067,1350000,69000000,96.7,81.81,0.02
17,South Africa,59308690,410000,43000000,95.0,72.50,0.01
18,Argentina,45195774,640000,41000000,99.1,90.72,0.01
19,Netherlands,17441139,1150000,17000000,99.0,97.47,0.07
20,Switzerland,8654622,940000,8500000,99.0,98.21,0.11
21,Sweden,10353442,650000,10100000,99.0,97.55,0.06
22,Norway,5421241,580000,5300000,100.0,97.76,0.11
23,Singapore,5850342,530000,5600000,97.5,95.72,0.09

In [ ]:
query='''SELECT *
FROM country_statistics
ORDER BY "Internet Penetration (%)" DESC
LIMIT 5;'''
result=pd.read_sql(query,connection)
display(result)

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,Switzerland,8654622,940000,8500000,99.0,98.21,0.11
1,Norway,5421241,580000,5300000,100.0,97.76,0.11
2,Saudi Arabia,34813871,1100000,34000000,97.3,97.66,0.03
3,Sweden,10353442,650000,10100000,99.0,97.55,0.06
4,Netherlands,17441139,1150000,17000000,99.0,97.47,0.07

In [ ]:
query='''SELECT SUM(Population)
FROM country_statistics;'''
result=pd.read_sql(query,connection)
display(result)

   SUM(Population)
0       4720039725

In [ ]:
query='''SELECT *
FROM country_statistics
ORDER BY "GDP Per Capita" DESC
LIMIT 1;'''
result=pd.read_sql(query,connection)
display(result)

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,Switzerland,8654622,940000,8500000,99.0,98.21,0.11

In [ ]:
merged.to_csv(
"final_country_statistics.csv",
index=False
)

In [ ]:
print(
merged.sort_values(
by="GDP Per Capita",
ascending=False
).head(10)
)

           country  population       GDP  internet_users  literacy_rate  \
21     Switzerland     8654622    940000         8500000           99.0
23          Norway     5421241    580000         5300000          100.0
24       Singapore     5850342    530000         5600000           97.5
0    United States   331002651  30500000       312000000           99.0
9        Australia    25687041   1880000        24000000           99.0
20     Netherlands    17441139   1150000        17000000           99.0
4          Germany    83240525   4744000        79000000           99.0
8           Canada    38005238   2250000        36000000           99.0
5   United Kingdom    67886011   3839000        66000000           99.0
22          Sweden    10353442    650000        10100000           99.0

    Internet Penetration (%)  GDP Per Capita
21                     98.21            0.11
23                     97.76            0.11
24                     95.72            0.09
0                      94.26            0.09
9                      93.43            0.07
20                     97.47            0.07
4                      94.91            0.06
8                      94.72            0.06
5                      97.22            0.06
22                     97.55            0.06