<a href="https://colab.research.google.com/github/akashms011-create/demo/blob/main/Pandas_activity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1
import numpy as np
import pandas as pd
df = pd.read_csv('/content/titanic_dataset.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
("\n--- Q2: Missing values per column ---")
df
(df.isnull().sum())
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
#3
print("\n--- Q3: Survival percentage by gender ---")
survival_by_gender = df.groupby('Sex')['Survived'].mean() * 100
print(survival_by_gender)

--- Q3: Survival percentage by gender ---
Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64

In [ ]:
#4
print("\n--- Q4: Age Statistics (Average, Median, Std Dev) ---")
age_stats = df['Age'].agg(['mean', 'median', 'std'])
print(age_stats)

--- Q4: Age Statistics (Average, Median, Std Dev) ---
mean      29.699118
median    28.000000
std       14.526497
Name: Age, dtype: float64

In [ ]:
#5
print("\n--- Q5: Passenger count by class ---")
class_counts = df['Pclass'].value_counts().sort_index()
print(class_counts)

--- Q5: Passenger count by class ---
Pclass
1    216
2    184
3    491
Name: count, dtype: int64

In [ ]:
#6
("\n--- Q6: Female, under 18, and survived ---")
df
young_female_survivors = df[(df['Sex'] == 'female') & (df['Age'] < 18) & (df['Survived'] == 1)]
(young_female_survivors)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
#7
print("\n--- Q7: Replacing missing ages with median ---")
median_age = df['Age'].median()
df['Age'] = df['Age'].fillna(median_age)
print(f"Missing 'Age' values after replacement: {df['Age'].isnull().sum()}")

--- Q7: Replacing missing ages with median ---
Missing 'Age' values after replacement: 0

In [ ]:
#8
print("\n--- Q8: Creating age_group column ---")
def categorize_age(age):
    if age < 18:
        return 'Child'
    elif age <= 60:
        return 'Adult'
    else:
        return 'Senior'

df['age_group'] = df['Age'].apply(categorize_age)
print(df[['Age', 'age_group']].head())

--- Q8: Creating age_group column ---
    Age age_group
0  22.0     Adult
1  38.0     Adult
2  26.0     Adult
3  35.0     Adult
4  35.0     Adult

In [ ]:
#9
print("\n--- Q9: Top 5 highest fares ---")
top_fares = df.nlargest(5, 'Fare')
print(top_fares[['Name', 'Fare']])

--- Q9: Top 5 highest fares ---
                                   Name      Fare
258                    Ward, Miss. Anna  512.3292
679  Cardeza, Mr. Thomas Drake Martinez  512.3292
737              Lesurer, Mr. Gustave J  512.3292
27       Fortune, Mr. Charles Alexander  263.0000
88           Fortune, Miss. Mabel Helen  263.0000

In [ ]:
#10
print("\n--- Q10: Average fare by class and sex ---")
avg_fare_grouped = df.groupby(['Pclass', 'Sex'])['Fare'].mean()
print(avg_fare_grouped)

--- Q10: Average fare by class and sex ---
Pclass  Sex
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: Fare, dtype: float64

In [ ]:
#11
print("\n--- Q11: Renaming columns ---")
df = df.rename(columns={'Sex': 'gender', 'Fare': 'ticket_fare'})
print("Current columns:", df.columns.tolist())

--- Q11: Renaming columns ---
Current columns: ['PassengerId', 'Survived', 'Pclass', 'Name', 'gender', 'Age', 'SibSp', 'Parch', 'Ticket', 'ticket_fare', 'Cabin', 'Embarked', 'age_group']

In [ ]:
#12
print("\n--- Q12: Survival counts by class ---")
survival_counts_by_class = df.groupby(['Pclass', 'Survived']).size()
print(survival_counts_by_class)

--- Q12: Survival counts by class ---
Pclass  Survived
1       0            80
        1           136
2       0            97
        1            87
3       0           372
        1           119
dtype: int64

In [ ]:
#13
import pandas as pd
if 'gender' not in df.columns:
    df = df.rename(columns={'Sex': 'gender'})

print("\n--- Q13: Average age by class and gender ---")
avg_age_grouped = df.groupby(['Pclass', 'gender'])['Age'].mean()
print(avg_age_grouped)

--- Q13: Average age by class and gender ---
Pclass  gender
1       female    34.611765
        male      41.281386
2       female    28.722973
        male      30.740707
3       female    21.750000
        male      26.507589
Name: Age, dtype: float64